openclassroomscourse_platform_index:
    path:     /adverts
    defaults:
        _controller: OpenClassroomsCoursePlatformBundle:Advert:index
    requirements:
    methods:  [GET]

openclassroomscourse_platform_view:
    path:     /adverts/{id}
    defaults:
        _controller: OpenClassroomsCoursePlatformBundle:Advert:view
    requirements:
        id: \d+
    methods:  [GET]

openclassroomscourse_platform_edit:
    path:     /adverts/{id}/edit
    defaults:
        _controller: OpenClassroomsCoursePlatformBundle:Advert:edit
    requirements:
        id: \d+
    methods:  [GET]

openclassroomscourse_platform_add:
    path:     /adverts
    defaults:
        _controller: OpenClassroomsCoursePlatformBundle:Advert:add
    methods:  [POST]

openclassroomscourse_platform_patch:
    path:     /adverts/{id}
    defaults:
        _controller: OpenClassroomsCoursePlatformBundle:Advert:patch
    requirements:
        id: \d+
    methods:  [PATCH]

openclassroomscourse_platform_delete:
    path:     /adverts/{id}
    defaults:
        _controller: OpenClassroomsCoursePlatformBundle:Advert:delete
    requirements:
        id: \d+
    methods:  [DELETE]

openclassroomscourse_platform_view_slug:
    path:      /{year}/{author}.{format}
    defaults:
        _controller: OpenClassroomsCoursePlatformBundle:Advert:viewSlug
        format:      html
    requirements:
        year:   \d{4}
        author: \w+
        format: html|json
    methods:  [GET]

openclassroomscourse_platform_redirect:
    path:      /redirect
    defaults:
        _controller: OpenClassroomsCoursePlatformBundle:Advert:redirect
    methods:  [GET]

openclassroomscourse_session_get:
    path:      /session
    defaults:
        _controller: OpenClassroomsCoursePlatformBundle:Advert:getSession
        format:      json
    methods:  [GET]

openclassroomscourse_session_patch:
    path:      /session
    defaults:
        _controller: OpenClassroomsCoursePlatformBundle:Advert:patchSession
        format:      json
    methods:  [PATCH]

openclassroomscourse_session_start:
    path:      /session/start
    defaults:
        _controller: OpenClassroomsCoursePlatformBundle:Advert:startSession
    methods:  [POST]
