services:
#    open_classrooms_course_platform.example:
#        class: OpenClassroomsCourse\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

services:
    openclassroomscourse_platform.spam_filter:
        class: OpenClassroomsCourse\PlatformBundle\Filter\SpamFilter
        arguments:
            - %antispamMinContentLength%